AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Voice Matrix Backend with VAPI Integration

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        REGION: eu-north-1
        USERS_TABLE: voice-matrix-users
        CALLS_TABLE: voice-matrix-calls
        ANALYTICS_TABLE: voice-matrix-analytics
        VAPI_SYNC_TABLE: voice-matrix-vapi-sync
        PHONE_NUMBERS_TABLE: voice-matrix-phone-numbers
        ASSISTANTS_TABLE: voice-matrix-assistants
        USER_ASSISTANTS_TABLE: voice-matrix-user-assistants
        ENCRYPTION_KEY: !Ref EncryptionKey
        VAPI_API_KEY: !Ref VapiApiKey
        TWILIO_CREDENTIAL_ID: !Ref TwilioCredentialId

Parameters:
  EncryptionKey:
    Type: String
    Description: Encryption key for sensitive data
    NoEcho: true
    Default: "your-32-byte-encryption-key-here"
  
  VapiApiKey:
    Type: String
    Description: VAPI API key for assistant and phone management
    NoEcho: true
    Default: "661b91f4-60e3-457e-820a-1dc7987b2b1c"
  
  TwilioCredentialId:
    Type: String
    Description: Twilio credential ID in VAPI for phone number provisioning
    NoEcho: true
    Default: "your-twilio-credential-id"

Resources:
  # API Gateway
  VoiceMatrixApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/eu-north-1_RvDRR8Kgr'

  # User Management Functions
  GetUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.getUserProfile
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/profile
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  UpdateUserProfile:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.updateUserProfile
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/profile
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  SaveVapiCredentials:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.saveVapiCredentials
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/vapi-credentials
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  GetVapiCredentials:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.getVapiCredentials
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/vapi-credentials
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  RemoveVapiCredentials:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.removeVapiCredentials
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/vapi-credentials
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  # VAPI Integration Functions
  GetVapiAssistants:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.getAssistants
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  CreateVapiAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.createAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants
            Method: POST
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  UpdateVapiAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.updateAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants/{assistantId}
            Method: PATCH
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  DeleteVapiAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.deleteAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants/{assistantId}
            Method: DELETE
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  GetVapiCalls:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.getVapiCalls
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/calls
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  # Assistant Management Functions
  CreateAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.createAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistantsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserAssistantsTable

  GetAssistants:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.getAssistants
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AssistantsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UserAssistantsTable

  UpdateAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.updateAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants/{assistantId}
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistantsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserAssistantsTable

  DeleteAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.deleteAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants/{assistantId}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AssistantsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserAssistantsTable

  LinkPhoneToAssistant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.linkPhoneToAssistant
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/assistants/{assistantId}/link-phone
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserAssistantsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PhoneNumbersTable

  GetAssistantTemplates:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-assistants.getTemplates
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/templates
            Method: GET
            Auth:
              Authorizer: NONE
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AssistantsTable

  # Phone Number Management Functions
  CreateVapiPhoneNumber:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-phone-numbers.createPhoneNumber
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/phone-numbers
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PhoneNumbersTable

  GetVapiPhoneNumber:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-phone-numbers.getPhoneNumber
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/phone-numbers
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PhoneNumbersTable

  UpdateVapiPhoneNumber:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-phone-numbers.updatePhoneNumber
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/phone-numbers/{phoneNumberId}
            Method: PATCH
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PhoneNumbersTable

  DeleteVapiPhoneNumber:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-phone-numbers.deletePhoneNumber
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /vapi/phone-numbers/{phoneNumberId}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PhoneNumbersTable

  # VAPI Webhook Handler (No Auth Required)
  VapiWebhookHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-webhook.handleWebhook
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /webhook/vapi
            Method: POST
            Auth:
              Authorizer: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CallsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AnalyticsTable
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable

  # Data Sync Functions
  VapiSyncScheduler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-sync.syncVapiData
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CallsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AnalyticsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref VapiSyncTable

  SyncUserData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: vapi-sync.syncUserData
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/sync
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CallsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AnalyticsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref VapiSyncTable

  GetSyncStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: user-management.getSyncStatus
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /user/sync-status
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref VapiSyncTable

  # Legacy Dashboard Functions (Updated for VAPI)
  GetDashboardData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dashboard.handler
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /dashboard
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CallsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AnalyticsTable

  GetCallLogs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: calls.getCallLogs
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref VoiceMatrixApi
            Path: /calls
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CallsTable

  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-users
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CallsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-calls
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: callId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: callId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  AnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-analytics
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  VapiSyncTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-vapi-sync
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: syncType
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: syncType
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  PhoneNumbersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-phone-numbers
      AttributeDefinitions:
        - AttributeName: phoneNumberId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: phoneNumberId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  AssistantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-assistants
      AttributeDefinitions:
        - AttributeName: assistantId
          AttributeType: S
        - AttributeName: templateName
          AttributeType: S
      KeySchema:
        - AttributeName: assistantId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: template-index
          KeySchema:
            - AttributeName: templateName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  UserAssistantsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: voice-matrix-user-assistants
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: assistantId
          AttributeType: S
        - AttributeName: phoneNumber
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: assistantId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: phoneNumber-index
          KeySchema:
            - AttributeName: phoneNumber
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

Outputs:
  VoiceMatrixApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${VoiceMatrixApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  VapiWebhookUrl:
    Description: "VAPI Webhook endpoint URL"
    Value: !Sub "https://${VoiceMatrixApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook/vapi"
    Export:
      Name: !Sub "${AWS::StackName}-WebhookUrl"